### ISSUE TITLE
there are 2 rules missing from byl's loop

### ISSUE THREAD

**Issue by Yolsh** [timhutton/ruletablerepository#8]
Hi there are 2 rules you are missing from Byl's loop. they are rule 334223 and rule 212042. also it would be really great if this repository also contained the starting configurations for the loop CA's as i struggled for hours getting mine working in Processing.

**Comment by timhutton** [comment]
Hi @Yolsh 

Did you look at Golly? It has a working pattern.

**Comment by Yolsh** [comment]
Yeah im aware that golly has it working but i was impementing it my self and thought that if anyone else went looking for these rulesets (very hard to find) it would help out. Mine worked after i added them and didnt work before the. Does golly pull durect from this repository for its ruleset or is it more of a backup?

**Comment by dvgrn** [comment]
At this point, I think that the standard repository location for rule
tables has definitely shifted to the LifeWiki:

  https://conwaylife.com/wiki/List_of_rule_tables_on_LifeWiki

I know of at least a fair number of rules and collections in the Rule Table
Repository that are out of date in various ways, and of course there are a
very large number of rule definitions commonly discussed on the
conwaylife.com forums, that aren't represented in the old RTR at all.

There has been only a small amount of maintenance done there since the
site's creation nine years ago (carried over from an older googlecode
site).  With a new release of Golly coming out, maybe now would be a good
time to remove any remaining links to the RTR?

Keep the cheer,


Dave

**Comment by timhutton** [comment]
Thanks all.

I've added a note to says that the RTR is out of date.

I'd be happy for Golly to remove its link to the RTR.

**Comment by andykt** [comment]
Dave:

> With a new release of Golly coming out, maybe now would be a good
> time to remove any remaining links to the RTR?

I'd really prefer to keep those links, at least for a while.
A number of zip files on the RTR contain really interesting pattern
collections along with their rule(s):  Snakes.zip, Squaredance.zip,
MazeSolver.zip, to name just a few.

Maybe it's time to clean up a lot of those zips (delete the deprecated
files, etc) and maybe include the best in a future version of Golly.
Probably not enough time to decide on this for the 4.3 release
but next year is Golly's 20th anniversary so I'm already thinking
about doing a special Golly 5.0 release in 2025.  That should give
us plenty of time to decide what to do with the RTR!

Andrew

**Comment by dvgrn** [comment]
Sounds good to me -- one less thing to think about for Golly 4.3!

Thanks,


Dave
